name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install & Build Bun components
        working-directory: cmd/daemon/components/login/next
        run: |
          bun install --frozen-lockfile || bun install
          bun run build

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Daemon
        run: |
          cp cmd/daemon/src/rsrc_windows_amd64.syso cmd/daemon || copy cmd\daemon\src\rsrc_windows_amd64.syso cmd\daemon
          go build -o vrpaws-client-${{ github.ref_name }}.exe ./cmd/daemon
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vrpaws-client-${{ github.ref_name }}.exe
          path: vrpaws-client-${{ github.ref_name }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: vrpaws-client-*
          merge-multiple: true
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: vrpaws-client-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
